name: GijirokuApp
options:
  bundleIdPrefix: com.gijiroku
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: 1
    CODE_SIGN_STYLE: Automatic

packages:
  WhisperKit:
    url: https://github.com/argmaxinc/WhisperKit.git
    from: "0.9.0"
  Supabase:
    url: https://github.com/supabase/supabase-swift.git
    from: "2.0.0"

targets:
  GijirokuApp:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: GijirokuApp
    settings:
      base:
        INFOPLIST_FILE: GijirokuApp/App/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.gijiroku.app
        TARGETED_DEVICE_FAMILY: "1"
    dependencies:
      - package: WhisperKit
      - package: Supabase
        product: Supabase

  GijirokuAppTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: GijirokuAppTests
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: GijirokuApp
