name: GijirokuApp
options:
  bundleIdPrefix: com.gijiroku
  deploymentTarget:
    iOS: "26.0"
    watchOS: "26.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true
  groupSortPosition: top

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: 1
    CODE_SIGN_STYLE: Automatic

packages:
  Supabase:
    url: https://github.com/supabase/supabase-swift.git
    from: "2.0.0"

targets:
  GijirokuApp:
    type: application
    platform: iOS
    deploymentTarget: "26.0"
    sources:
      - path: GijirokuApp
    resources:
      - path: GijirokuApp/Resources/PrivacyInfo.xcprivacy
    settings:
      base:
        INFOPLIST_FILE: GijirokuApp/App/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.gijiroku.app
        TARGETED_DEVICE_FAMILY: "1"
        CODE_SIGN_ENTITLEMENTS: GijirokuApp/App/GijirokuApp.entitlements
    dependencies:
      - package: Supabase
        product: Supabase

  GijirokuWatch:
    type: application
    platform: watchOS
    deploymentTarget: "26.0"
    sources:
      - path: GijirokuWatch
    settings:
      base:
        INFOPLIST_FILE: GijirokuWatch/App/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.gijiroku.watch
        GENERATE_INFOPLIST_FILE: NO

  GijirokuAppTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: GijirokuAppTests
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: GijirokuApp

schemes:
  GijirokuApp:
    build:
      targets:
        GijirokuApp: all
        GijirokuAppTests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - GijirokuAppTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
  GijirokuWatch:
    build:
      targets:
        GijirokuWatch: all
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
